name: dominoes
description: domino counter

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  url_launcher: ^6.1.0
  auto_size_text: ^3.0.0
  path_provider: ^2.0.9
  font_awesome_flutter: ^10.1.0
  package_info_plus: ^5.0.1
  page_transition: ^2.0.5
  flutter_svg: ^2.0.5
  permission_handler: ^11.2.1
  camera: ^0.10.5
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/pips/
    - assets/images/
